// Code generated by qtc from "metrics_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/tempo/metrics_response.qtpl:1
package tempo

//line app/vtselect/traces/tempo/metrics_response.qtpl:1
import (
	"strconv"
)

//line app/vtselect/traces/tempo/metrics_response.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/tempo/metrics_response.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/tempo/metrics_response.qtpl:7
func StreamMetricsQueryRangeResponse(qw422016 *qt422016.Writer, series []tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:7
	qw422016.N().S(`{"series":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:10
	if len(series) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:11
		streammetricsSeriesJson(qw422016, &series[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:12
		for i := 1; i < len(series); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:12
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:13
			streammetricsSeriesJson(qw422016, &series[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:14
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:15
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:15
	qw422016.N().S(`],"metrics":{"inspectedBytes":"0","inspectedTraces":0,"totalJobs":0,"completedJobs":0},"status":"COMPLETE"}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:25
func WriteMetricsQueryRangeResponse(qq422016 qtio422016.Writer, series []tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	StreamMetricsQueryRangeResponse(qw422016, series)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:25
func MetricsQueryRangeResponse(series []tempoMetricsSeries) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	WriteMetricsQueryRangeResponse(qb422016, series)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:25
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:27
func streammetricsSeriesJson(qw422016 *qt422016.Writer, s *tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:27
	qw422016.N().S(`{"labels":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:30
	if len(s.Labels) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:31
		streammetricsLabelJson(qw422016, &s.Labels[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:32
		for i := 1; i < len(s.Labels); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:32
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:33
			streammetricsLabelJson(qw422016, &s.Labels[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:34
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:35
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:35
	qw422016.N().S(`],"samples":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:38
	if len(s.Samples) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:39
		streammetricsSampleJson(qw422016, &s.Samples[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:40
		for i := 1; i < len(s.Samples); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:40
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:41
			streammetricsSampleJson(qw422016, &s.Samples[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:42
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:43
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:43
	qw422016.N().S(`],"exemplars":[`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:46
	if len(s.Exemplars) > 0 {
//line app/vtselect/traces/tempo/metrics_response.qtpl:47
		streammetricsExemplarJson(qw422016, &s.Exemplars[0])
//line app/vtselect/traces/tempo/metrics_response.qtpl:48
		for i := 1; i < len(s.Exemplars); i++ {
//line app/vtselect/traces/tempo/metrics_response.qtpl:48
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:49
			streammetricsExemplarJson(qw422016, &s.Exemplars[i])
//line app/vtselect/traces/tempo/metrics_response.qtpl:50
		}
//line app/vtselect/traces/tempo/metrics_response.qtpl:51
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:51
	qw422016.N().S(`]}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:54
func writemetricsSeriesJson(qq422016 qtio422016.Writer, s *tempoMetricsSeries) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	streammetricsSeriesJson(qw422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:54
func metricsSeriesJson(s *tempoMetricsSeries) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	writemetricsSeriesJson(qb422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:54
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:56
func streammetricsExemplarJson(qw422016 *qt422016.Writer, e *tempoExemplar) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:56
	qw422016.N().S(`{"labels":[{"key":"trace:id","value":{"stringValue":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:59
	qw422016.N().Q(e.TraceID)
//line app/vtselect/traces/tempo/metrics_response.qtpl:59
	qw422016.N().S(`}},{"key":"span:id","value":{"stringValue":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:60
	qw422016.N().Q(e.SpanID)
//line app/vtselect/traces/tempo/metrics_response.qtpl:60
	qw422016.N().S(`}}],"value":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:62
	qw422016.N().F(e.Value)
//line app/vtselect/traces/tempo/metrics_response.qtpl:62
	qw422016.N().S(`,"timestampMs":"`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qw422016.N().S(strconv.FormatInt(e.TimestampMs, 10))
//line app/vtselect/traces/tempo/metrics_response.qtpl:63
	qw422016.N().S(`"}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:65
func writemetricsExemplarJson(qq422016 qtio422016.Writer, e *tempoExemplar) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	streammetricsExemplarJson(qw422016, e)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:65
func metricsExemplarJson(e *tempoExemplar) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	writemetricsExemplarJson(qb422016, e)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:65
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:67
func streammetricsLabelJson(qw422016 *qt422016.Writer, l *tempoLabel) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:67
	qw422016.N().S(`{"key":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:69
	qw422016.N().Q(l.Key)
//line app/vtselect/traces/tempo/metrics_response.qtpl:69
	qw422016.N().S(`,"value":{`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:71
	if l.Numeric {
//line app/vtselect/traces/tempo/metrics_response.qtpl:71
		qw422016.N().S(`"doubleValue":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:72
		qw422016.N().S(l.Value)
//line app/vtselect/traces/tempo/metrics_response.qtpl:73
	} else {
//line app/vtselect/traces/tempo/metrics_response.qtpl:73
		qw422016.N().S(`"stringValue":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:74
		qw422016.N().Q(l.Value)
//line app/vtselect/traces/tempo/metrics_response.qtpl:75
	}
//line app/vtselect/traces/tempo/metrics_response.qtpl:75
	qw422016.N().S(`}}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:78
func writemetricsLabelJson(qq422016 qtio422016.Writer, l *tempoLabel) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	streammetricsLabelJson(qw422016, l)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:78
func metricsLabelJson(l *tempoLabel) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	writemetricsLabelJson(qb422016, l)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:78
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:80
func streammetricsSampleJson(qw422016 *qt422016.Writer, s *tempoSample) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:80
	qw422016.N().S(`{"timestampMs":"`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:82
	qw422016.N().S(strconv.FormatInt(s.TimestampMs, 10))
//line app/vtselect/traces/tempo/metrics_response.qtpl:82
	qw422016.N().S(`","value":`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:83
	qw422016.N().F(s.Value)
//line app/vtselect/traces/tempo/metrics_response.qtpl:83
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:85
func writemetricsSampleJson(qq422016 qtio422016.Writer, s *tempoSample) {
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	streammetricsSampleJson(qw422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
}

//line app/vtselect/traces/tempo/metrics_response.qtpl:85
func metricsSampleJson(s *tempoSample) string {
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	writemetricsSampleJson(qb422016, s)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
	return qs422016
//line app/vtselect/traces/tempo/metrics_response.qtpl:85
}
