// Code generated by qtc from "tempo.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vtselect/traces/tempo/tempo.qtpl:1
package tempo

//line app/vtselect/traces/tempo/tempo.qtpl:1
import (
	"sort"
	"strconv"
)

//line app/vtselect/traces/tempo/tempo.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vtselect/traces/tempo/tempo.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vtselect/traces/tempo/tempo.qtpl:8
func StreamSearchTagsResponse(qw422016 *qt422016.Writer, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:8
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tempo.qtpl:11
	sort.Slice(resourceTagList, func(i, j int) bool { return resourceTagList[i] < resourceTagList[j] })
	sort.Slice(spanTagList, func(i, j int) bool { return spanTagList[i] < spanTagList[j] })
	sort.Slice(eventTagList, func(i, j int) bool { return eventTagList[i] < eventTagList[j] })
	sort.Slice(linkTagList, func(i, j int) bool { return linkTagList[i] < linkTagList[j] })
	sort.Slice(instrumentationScopeTagList, func(i, j int) bool { return instrumentationScopeTagList[i] < instrumentationScopeTagList[j] })

//line app/vtselect/traces/tempo/tempo.qtpl:16
	qw422016.N().S(`"scopes":[{"name": "resource","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:21
	if len(resourceTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:22
		qw422016.N().Q(resourceTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:23
		for _, tag := range resourceTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:23
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:24
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:25
		}
//line app/vtselect/traces/tempo/tempo.qtpl:26
	}
//line app/vtselect/traces/tempo/tempo.qtpl:26
	qw422016.N().S(`]},{"name": "span","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:32
	if len(spanTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:33
		qw422016.N().Q(spanTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:34
		for _, tag := range spanTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:34
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:35
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:36
		}
//line app/vtselect/traces/tempo/tempo.qtpl:37
	}
//line app/vtselect/traces/tempo/tempo.qtpl:37
	qw422016.N().S(`]},{"name": "event","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:43
	if len(eventTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:44
		qw422016.N().Q(eventTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:45
		for _, tag := range eventTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:45
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:46
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:47
		}
//line app/vtselect/traces/tempo/tempo.qtpl:48
	}
//line app/vtselect/traces/tempo/tempo.qtpl:48
	qw422016.N().S(`]},{"name": "link","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:54
	if len(linkTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:55
		qw422016.N().Q(linkTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:56
		for _, tag := range linkTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:56
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:57
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:58
		}
//line app/vtselect/traces/tempo/tempo.qtpl:59
	}
//line app/vtselect/traces/tempo/tempo.qtpl:59
	qw422016.N().S(`]},{"name": "instrumentation","tags": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:65
	if len(instrumentationScopeTagList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:66
		qw422016.N().Q(instrumentationScopeTagList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:67
		for _, tag := range instrumentationScopeTagList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:67
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:68
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:69
		}
//line app/vtselect/traces/tempo/tempo.qtpl:70
	}
//line app/vtselect/traces/tempo/tempo.qtpl:70
	qw422016.N().S(`]}],"metrics": {"inspectedBytes": "0"}}`)
//line app/vtselect/traces/tempo/tempo.qtpl:78
}

//line app/vtselect/traces/tempo/tempo.qtpl:78
func WriteSearchTagsResponse(qq422016 qtio422016.Writer, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:78
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:78
	StreamSearchTagsResponse(qw422016, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList)
//line app/vtselect/traces/tempo/tempo.qtpl:78
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:78
}

//line app/vtselect/traces/tempo/tempo.qtpl:78
func SearchTagsResponse(resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList []string) string {
//line app/vtselect/traces/tempo/tempo.qtpl:78
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:78
	WriteSearchTagsResponse(qb422016, resourceTagList, spanTagList, eventTagList, linkTagList, instrumentationScopeTagList)
//line app/vtselect/traces/tempo/tempo.qtpl:78
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:78
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:78
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:78
}

//line app/vtselect/traces/tempo/tempo.qtpl:80
func StreamSearchTagValuesResponse(qw422016 *qt422016.Writer, tagValueList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:80
	qw422016.N().S(`{`)
//line app/vtselect/traces/tempo/tempo.qtpl:83
	sort.Slice(tagValueList, func(i, j int) bool { return tagValueList[i] < tagValueList[j] })

//line app/vtselect/traces/tempo/tempo.qtpl:84
	qw422016.N().S(`"tagValues":[`)
//line app/vtselect/traces/tempo/tempo.qtpl:86
	if len(tagValueList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:86
		qw422016.N().S(`{"type": "string","value":`)
//line app/vtselect/traces/tempo/tempo.qtpl:89
		qw422016.N().Q(tagValueList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:89
		qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:91
	}
//line app/vtselect/traces/tempo/tempo.qtpl:92
	if len(tagValueList) > 1 {
//line app/vtselect/traces/tempo/tempo.qtpl:93
		for _, tag := range tagValueList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:93
			qw422016.N().S(`,{"type": "string","value":`)
//line app/vtselect/traces/tempo/tempo.qtpl:96
			qw422016.N().Q(tag)
//line app/vtselect/traces/tempo/tempo.qtpl:96
			qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:98
		}
//line app/vtselect/traces/tempo/tempo.qtpl:99
	}
//line app/vtselect/traces/tempo/tempo.qtpl:99
	qw422016.N().S(`],"metrics": {"inspectedBytes": "0"}}`)
//line app/vtselect/traces/tempo/tempo.qtpl:105
}

//line app/vtselect/traces/tempo/tempo.qtpl:105
func WriteSearchTagValuesResponse(qq422016 qtio422016.Writer, tagValueList []string) {
//line app/vtselect/traces/tempo/tempo.qtpl:105
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:105
	StreamSearchTagValuesResponse(qw422016, tagValueList)
//line app/vtselect/traces/tempo/tempo.qtpl:105
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:105
}

//line app/vtselect/traces/tempo/tempo.qtpl:105
func SearchTagValuesResponse(tagValueList []string) string {
//line app/vtselect/traces/tempo/tempo.qtpl:105
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:105
	WriteSearchTagValuesResponse(qb422016, tagValueList)
//line app/vtselect/traces/tempo/tempo.qtpl:105
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:105
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:105
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:105
}

//line app/vtselect/traces/tempo/tempo.qtpl:107
func StreamSearchResponse(qw422016 *qt422016.Writer, summaryList []traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:107
	qw422016.N().S(`{"traces": [`)
//line app/vtselect/traces/tempo/tempo.qtpl:110
	if len(summaryList) > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:111
		streamsummaryJson(qw422016, summaryList[0])
//line app/vtselect/traces/tempo/tempo.qtpl:112
		for _, summary := range summaryList[1:] {
//line app/vtselect/traces/tempo/tempo.qtpl:112
			qw422016.N().S(`,`)
//line app/vtselect/traces/tempo/tempo.qtpl:113
			streamsummaryJson(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:114
		}
//line app/vtselect/traces/tempo/tempo.qtpl:115
	}
//line app/vtselect/traces/tempo/tempo.qtpl:115
	qw422016.N().S(`]}`)
//line app/vtselect/traces/tempo/tempo.qtpl:118
}

//line app/vtselect/traces/tempo/tempo.qtpl:118
func WriteSearchResponse(qq422016 qtio422016.Writer, summaryList []traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:118
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:118
	StreamSearchResponse(qw422016, summaryList)
//line app/vtselect/traces/tempo/tempo.qtpl:118
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:118
}

//line app/vtselect/traces/tempo/tempo.qtpl:118
func SearchResponse(summaryList []traceSummary) string {
//line app/vtselect/traces/tempo/tempo.qtpl:118
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:118
	WriteSearchResponse(qb422016, summaryList)
//line app/vtselect/traces/tempo/tempo.qtpl:118
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:118
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:118
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:118
}

//line app/vtselect/traces/tempo/tempo.qtpl:120
func streamsummaryJson(qw422016 *qt422016.Writer, summary traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:120
	qw422016.N().S(`{"traceID":`)
//line app/vtselect/traces/tempo/tempo.qtpl:122
	qw422016.N().Q(summary.traceID)
//line app/vtselect/traces/tempo/tempo.qtpl:122
	qw422016.N().S(`,"rootServiceName":`)
//line app/vtselect/traces/tempo/tempo.qtpl:123
	qw422016.N().Q(summary.rootServiceName)
//line app/vtselect/traces/tempo/tempo.qtpl:123
	qw422016.N().S(`,"rootTraceName":`)
//line app/vtselect/traces/tempo/tempo.qtpl:124
	qw422016.N().Q(summary.rootTraceName)
//line app/vtselect/traces/tempo/tempo.qtpl:124
	qw422016.N().S(`,"startTimeUnixNano":`)
//line app/vtselect/traces/tempo/tempo.qtpl:125
	qw422016.N().DL(summary.startTimeUnixNano)
//line app/vtselect/traces/tempo/tempo.qtpl:125
	qw422016.N().S(`,"durationMs":`)
//line app/vtselect/traces/tempo/tempo.qtpl:126
	if summary.endTimeUnixNano > 0 && summary.startTimeUnixNano > 0 {
//line app/vtselect/traces/tempo/tempo.qtpl:126
		qw422016.N().DL((summary.endTimeUnixNano - summary.startTimeUnixNano) / 1e6)
//line app/vtselect/traces/tempo/tempo.qtpl:126
	} else {
//line app/vtselect/traces/tempo/tempo.qtpl:126
		qw422016.N().S(`0`)
//line app/vtselect/traces/tempo/tempo.qtpl:126
	}
//line app/vtselect/traces/tempo/tempo.qtpl:126
	qw422016.N().S(`,"spanSet":`)
//line app/vtselect/traces/tempo/tempo.qtpl:127
	streamspanSetJSON(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:127
	qw422016.N().S(`,"spanSets":[`)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	streamspanSetJSON(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:128
	qw422016.N().S(`]}`)
//line app/vtselect/traces/tempo/tempo.qtpl:130
}

//line app/vtselect/traces/tempo/tempo.qtpl:130
func writesummaryJson(qq422016 qtio422016.Writer, summary traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:130
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:130
	streamsummaryJson(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:130
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:130
}

//line app/vtselect/traces/tempo/tempo.qtpl:130
func summaryJson(summary traceSummary) string {
//line app/vtselect/traces/tempo/tempo.qtpl:130
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:130
	writesummaryJson(qb422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:130
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:130
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:130
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:130
}

//line app/vtselect/traces/tempo/tempo.qtpl:132
func streamspanSetJSON(qw422016 *qt422016.Writer, summary traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:132
	qw422016.N().S(`{"spans":[`)
//line app/vtselect/traces/tempo/tempo.qtpl:135
	if summary.rootSpanID != "" {
//line app/vtselect/traces/tempo/tempo.qtpl:135
		qw422016.N().S(`{"spanID":`)
//line app/vtselect/traces/tempo/tempo.qtpl:137
		qw422016.N().Q(summary.rootSpanID)
//line app/vtselect/traces/tempo/tempo.qtpl:137
		qw422016.N().S(`,"startTimeUnixNano":`)
//line app/vtselect/traces/tempo/tempo.qtpl:138
		qw422016.N().Q(strconv.FormatInt(summary.rootStartTimeUnixNano, 10))
//line app/vtselect/traces/tempo/tempo.qtpl:138
		qw422016.N().S(`,"durationNanos":`)
//line app/vtselect/traces/tempo/tempo.qtpl:139
		qw422016.N().Q(strconv.FormatInt(summary.rootEndTimeUnixNano-summary.rootStartTimeUnixNano, 10))
//line app/vtselect/traces/tempo/tempo.qtpl:139
		qw422016.N().S(`,"attributes":[{"key":"service.name","value":{"stringValue":`)
//line app/vtselect/traces/tempo/tempo.qtpl:141
		qw422016.N().Q(summary.rootServiceName)
//line app/vtselect/traces/tempo/tempo.qtpl:141
		qw422016.N().S(`}},{"key":"nestedSetParent","value":{"intValue":"-1"}}]}`)
//line app/vtselect/traces/tempo/tempo.qtpl:145
	}
//line app/vtselect/traces/tempo/tempo.qtpl:145
	qw422016.N().S(`],"matched":`)
//line app/vtselect/traces/tempo/tempo.qtpl:147
	if summary.rootSpanID != "" {
//line app/vtselect/traces/tempo/tempo.qtpl:147
		qw422016.N().S(`1`)
//line app/vtselect/traces/tempo/tempo.qtpl:147
	} else {
//line app/vtselect/traces/tempo/tempo.qtpl:147
		qw422016.N().S(`0`)
//line app/vtselect/traces/tempo/tempo.qtpl:147
	}
//line app/vtselect/traces/tempo/tempo.qtpl:147
	qw422016.N().S(`}`)
//line app/vtselect/traces/tempo/tempo.qtpl:149
}

//line app/vtselect/traces/tempo/tempo.qtpl:149
func writespanSetJSON(qq422016 qtio422016.Writer, summary traceSummary) {
//line app/vtselect/traces/tempo/tempo.qtpl:149
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vtselect/traces/tempo/tempo.qtpl:149
	streamspanSetJSON(qw422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:149
	qt422016.ReleaseWriter(qw422016)
//line app/vtselect/traces/tempo/tempo.qtpl:149
}

//line app/vtselect/traces/tempo/tempo.qtpl:149
func spanSetJSON(summary traceSummary) string {
//line app/vtselect/traces/tempo/tempo.qtpl:149
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vtselect/traces/tempo/tempo.qtpl:149
	writespanSetJSON(qb422016, summary)
//line app/vtselect/traces/tempo/tempo.qtpl:149
	qs422016 := string(qb422016.B)
//line app/vtselect/traces/tempo/tempo.qtpl:149
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vtselect/traces/tempo/tempo.qtpl:149
	return qs422016
//line app/vtselect/traces/tempo/tempo.qtpl:149
}
