// Code generated by qtc from "query_response.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line app/vlselect/logsql/query_response.qtpl:1
package logsql

//line app/vlselect/logsql/query_response.qtpl:1
import (
	"github.com/VictoriaMetrics/VictoriaLogs/lib/logstorage"
)

// JSONRows prints formatted rows

//line app/vlselect/logsql/query_response.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app/vlselect/logsql/query_response.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app/vlselect/logsql/query_response.qtpl:8
func StreamJSONRows(qw422016 *qt422016.Writer, rows [][]logstorage.Field) {
//line app/vlselect/logsql/query_response.qtpl:9
	if len(rows) == 0 {
//line app/vlselect/logsql/query_response.qtpl:10
		return
//line app/vlselect/logsql/query_response.qtpl:11
	}
//line app/vlselect/logsql/query_response.qtpl:12
	for _, fields := range rows {
//line app/vlselect/logsql/query_response.qtpl:13
		fields = logstorage.SkipLeadingFieldsWithoutValues(fields)

//line app/vlselect/logsql/query_response.qtpl:14
		if len(fields) == 0 {
//line app/vlselect/logsql/query_response.qtpl:15
			continue
//line app/vlselect/logsql/query_response.qtpl:16
		}
//line app/vlselect/logsql/query_response.qtpl:16
		qw422016.N().S(`{`)
//line app/vlselect/logsql/query_response.qtpl:19
		f := fields[0]
		fields = fields[1:]

//line app/vlselect/logsql/query_response.qtpl:22
		qw422016.N().Q(f.Name)
//line app/vlselect/logsql/query_response.qtpl:22
		qw422016.N().S(`:`)
//line app/vlselect/logsql/query_response.qtpl:22
		qw422016.N().Q(f.Value)
//line app/vlselect/logsql/query_response.qtpl:23
		for _, f := range fields {
//line app/vlselect/logsql/query_response.qtpl:24
			if f.Value == "" {
//line app/vlselect/logsql/query_response.qtpl:25
				continue
//line app/vlselect/logsql/query_response.qtpl:26
			}
//line app/vlselect/logsql/query_response.qtpl:26
			qw422016.N().S(`,`)
//line app/vlselect/logsql/query_response.qtpl:27
			qw422016.N().Q(f.Name)
//line app/vlselect/logsql/query_response.qtpl:27
			qw422016.N().S(`:`)
//line app/vlselect/logsql/query_response.qtpl:27
			qw422016.N().Q(f.Value)
//line app/vlselect/logsql/query_response.qtpl:28
		}
//line app/vlselect/logsql/query_response.qtpl:28
		qw422016.N().S(`}`)
//line app/vlselect/logsql/query_response.qtpl:29
		qw422016.N().S(`
`)
//line app/vlselect/logsql/query_response.qtpl:30
	}
//line app/vlselect/logsql/query_response.qtpl:31
}

//line app/vlselect/logsql/query_response.qtpl:31
func WriteJSONRows(qq422016 qtio422016.Writer, rows [][]logstorage.Field) {
//line app/vlselect/logsql/query_response.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line app/vlselect/logsql/query_response.qtpl:31
	StreamJSONRows(qw422016, rows)
//line app/vlselect/logsql/query_response.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line app/vlselect/logsql/query_response.qtpl:31
}

//line app/vlselect/logsql/query_response.qtpl:31
func JSONRows(rows [][]logstorage.Field) string {
//line app/vlselect/logsql/query_response.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line app/vlselect/logsql/query_response.qtpl:31
	WriteJSONRows(qb422016, rows)
//line app/vlselect/logsql/query_response.qtpl:31
	qs422016 := string(qb422016.B)
//line app/vlselect/logsql/query_response.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line app/vlselect/logsql/query_response.qtpl:31
	return qs422016
//line app/vlselect/logsql/query_response.qtpl:31
}
